sonar.projectKey=Livesim
sonar.projectName=LifeSim
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts
sonar.exclusions=**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
